name = "zapret-update-membership"
account_id = "1cbf29be6129f41bca11b253aa4d1003"
main = "src/worker.js"
compatibility_date = "2026-09-15"
workers_dev = true

[vars]
BOT_USERNAME = "ZapretLoLBot"
CHANNEL_ID = "@Slag0dworld"

[[d1_databases]]
binding = "DB"
database_name = "zapret-update-membership"
database_id = "921ca782-66d8-45f8-b673-08e3da6ce711"
migrations_dir = "migrations"

[observability]
enabled = false

[triggers]
crons = ["*/10 * * * *"]
